### PR TITLE
Add hpack as a built-tool so it could be invoked to get a cabal file

### PR DESCRIPTION
**Pull request by qrilka**
This and #39 give better integration with packages using hpack.
This PR requires https://github.com/input-output-hk/haskell.nix/pull/80

### CODE REVIEW

**Comment by angerman** [comment]
I'm a bit on the fence wrt to this PR. It starts opening the gate to the package modification that `cabal2nix` already does. 

I assume we want to use `hpack` if if the generator is set to `hpack` in the package. Why can't we just refer to `${pkgs.buildPackages.hpack}/bin/hpack` in the builder?

The issue right now (which doesn't really sit well with me) is:
1. We have an `package.yaml` file.
2. We run `hpack` to generate the corresponding `.cabal` file.
3. Now we inject `hpack` as a dependency into the cabal expression. But at this point we are far beyond the point where we actually need `hpack`.
4. We now translate a cabal expression into a nix-expression, but really we are generating something that's not a cabal to nix translation anymore.

**Comment by qrilka** [comment]
@angerman what do you think would be a better way here? Including generated file into a Nix expression maybe? That way we couldl have the same file for generating a Nix file and when building it.

**Comment by angerman** [comment]
@qrilka I would assume that `hpack` is deterministic.  And running `hpack` during the build is fine. I'm just not very happy with the idea of jamming `hpack` into the nix expression that was generated from a `cabal` file. Maybe the comments in input-output-hk/haskell.nix#80 make more sense of how this could be solved without changing nix-tools.

**Comment by qrilka** [comment]
Closed in favor of https://github.com/input-output-hk/haskell.nix/pull/82

**Pull request closed without merging**
