### PR TITLE
cabal-to-nix: add fallback to hpack when cabal file does not exist

### PR DESCRIPTION
**Pull request by yorickvP**
Also improve some errors. Fixes input-output-hk/haskell.nix#308 using the strategy outlined there. I'm currently running the build, but the planning stage works now.

### CODE REVIEW

**Comment by zhenyavinogradov** [comment]
From what I gather from the code it prefers package.yaml over .cabal files now

**Comment by angerman** [comment]
@zhenyavinogradov can you expand on that?

**Comment by zhenyavinogradov** [comment]
`findCabalFiles` check for package.yaml first, and only looks for .cabal files if it does not exist. And I tested this haskell.nix on a project containing both package.yaml and .cabal files, package.yaml has been used

**Comment by angerman** [comment]
@zhenyavinogradov alright, so the bias towards `package.yaml` files over `.cabal` files is preferrable or not in your view? I would have thought so. Isn't the usual situation `package.yaml -> .cabal` and if you start editing the `.cabal` file, you end up with two non-synchronous states?

**Comment by zhenyavinogradov** [comment]
It's an interesting question. I think for external dependencies you want to prefer .cabal because their package.yaml may use some features not supported by haskell.nix, such as relying on a template from github, but for packages you develop yourself you want to it to use package.yaml, because .cabal may happen to be out of sync during development

**Pull request merged**
